### ISSUE TITLE
Get in contact with the client (Thierry) and set an appointment with him.

### ISSUE THREAD

**Issue by amjadhz** [AutonomousVessel/Autonomous-Transport#18]
We have not heard from him for a long time so we need him to see our work so far and tell us if we are on the right track or not.
Note: If there is no answer from him in 3 days then contact teachers to find a solution for this.

**Comment by HelvisParadnieks** [comment]
Since Therry has not been responding we have talked to the teachers and a new client has been appointed to us - Milan Weug (weug0007@hz.nl)
